# 📘 Lesson 2: R Basics Refresher

Welcome to our second lesson in the research-oriented data mining course! Today, we'll dive deeper into the fundamentals of R programming that are essential for working with data. Don't worry if you're new to R; we'll go step-by-step.

## Learning Objectives

By the end of this lesson, you will be able to:

- Understand and use core R data types (numeric, character, logical, factor, date).
- Work with basic R data structures like vectors, lists, and data frames.
- Read data in mutiple ways.
- Get a preview of loading real-world data into R.

## 1 Basics of R

R is a powerful tool for all manner of calculations, data manipulation and scientific computations. Before
getting to the complex operations possible in R we must start with the basics. Like most languages R has
its share of mathematical capability , variables, functions and data types.

### 1.1 Basic Math

In [ ]:
1 + 2

[1] 3

In [ ]:
4 - 2

[1] 2

In [ ]:
3 * 4

[1] 12

In [ ]:
8 / 2

[1] 4

In [ ]:
8 / 3

[1] 2.666667

In [ ]:
2 + (4 - 1)

[1] 5

In [ ]:
8 / (4 - 2)

[1] 4

### 1.2 Variables

#### 1.2.1 Variable Assignment

The valid assignment operators are <- and =
, with the first being preferred.

In [ ]:
x <- 2
x

[1] 2

In [ ]:
y = 4
y

[1] 4

The arrow operator can also point in the other direction.

In [ ]:
6 -> z
z

[1] 6

The assignment operation can be used successively to assign a value to multiple variables
simultaneously .

In [ ]:
a <- b <- 12

In [ ]:
b

[1] 12

In [ ]:
a

[1] 12

In [ ]:
assign("j", 4) # function(parametere)

In [ ]:
j

[1] 4

#### 1.2.2 Removing V ariables

In [ ]:
j <- 3
j

[1] 3

In [ ]:
rm(j)

In [ ]:
j

ERROR: Error: object 'j' not found


Variable names are case sensitive (lowercase/uppercase)

In [ ]:
age <- 18
age

[1] 18

In [ ]:
age

[1] 18

In [ ]:
AGE

ERROR: Error: object 'AGE' not found


### 1.3 Data Types

There are numerous data types in R that store various kinds of data. The four main types of data most likely to be used are

- numeric: 1, 3, 2.5. 3.14
- character (string): 'Alice', 'US'. TEXT
- Date/POSIXct (time-based): 'Jan-02-2025'
- logical: TRUE/FALSE

In [ ]:
age <- 22
name <- 'Bob'
birthday <- as.Date('2021-05-02') # Use as.Date() with YYYY-MM-DD format
isHightSchool <- FALSE

print(age)
print(name)
print(birthday)
print(isHightSchool)

[1] 22
[1] "Bob"
[1] "2021-05-02"
[1] FALSE


Government expenditure on education, total (% of GDP)

In [ ]:
class(age)

[1] "numeric"

In [ ]:
class(name)

[1] "character"

In [ ]:
class(birthday)

[1] "Date"

In [ ]:
class(isHightSchool)

[1] "logical"

#### 1.3.1 Numeric Data

Testing whether a variable is numeric is done
with the function **is.numeric**

In [ ]:
is.numeric(age)

[1] TRUE

In [ ]:
is.numeric(name)

[1] FALSE

In [ ]:
is.function(name)

[1] FALSE

Another important, if less frequently used, type is integer. As the name implies this is for whole
numbers only , **no decimals**. To set an integer to a variable it is necessary to append the value with an **L**.
As with checking for a numeric, the **is.integer** function is used

In [ ]:
i <- 5

In [ ]:
is.numeric(i)

[1] TRUE

In [ ]:
is.integer(i)

[1] FALSE

In [ ]:
i <- 15L

In [ ]:
i

[1] 15

In [ ]:
is.numeric(i)

[1] TRUE

In [ ]:
is.integer(i)

[1] TRUE

In [ ]:
class(2L)

[1] "integer"

In [ ]:
class(2)

[1] "numeric"

In [ ]:
class(3.14)

[1] "numeric"

In [ ]:
is.integer(99L)

[1] TRUE

In [ ]:
5L * 3.14

[1] 15.7

In [ ]:
class(5L * 3.14)

[1] "numeric"

In [ ]:
5L / 2L

[1] 2.5

In [ ]:
class(5L / 2L)

[1] "numeric"

- modulus： %%
- integer division： %/%

In [ ]:
5 / 2

[1] 2.5

In [ ]:
5 %% 2

[1] 1

In [ ]:
5 %%/ 2

[1] 2

#### 1.3.2 Character Data

R has two primary ways of handling character data:
character and factor. While they may seem similar on the surface, they are treated quite differently .

In [ ]:
name <- 'Bob'
name

[1] "Bob"

In [ ]:
name <- "Bob"
name

In [ ]:
x <- 'data mining 12345 '
x

[1] "data mining 12345 "

In [ ]:
y <- factor('data mining 12345 ') # list/array
y

[1] data mining 12345 
Levels: data mining 12345

Characters are case sensitive, so “Data” is different from “data” or “DA T A”

In [ ]:
'data' == 'data'

[1] TRUE

In [ ]:
'data' == 'DATA'

[1] FALSE

To find the length of a character (or numeric) use the **nchar** function.

In [ ]:
x

[1] "data mining 12345 "

In [ ]:
nchar(x) # length

[1] 18

In [ ]:
nchar('datamining')

[1] 10

In [ ]:
nchar('hello')

[1] 5

In [ ]:
nchar(100)

[1] 3

In [ ]:
nchar(3.14)

[1] 4

In [ ]:
y <- factor('R programming')
y

[1] R programming
Levels: R programming

In [ ]:
nchar(y)

ERROR: Error in nchar(y): 'nchar()' requires a character vector


#### 1.3.3 Dates

Dealing with dates and times can be difficult in any language, and to further complicate matters R has
numerous different types of dates. The most useful are Date and POSIXct. Date stores just a date
while POSIXct stores a date and time. Both objects are actually represented as the number of days
(Date) or seconds (POSIXct) since January 1, 1970.

In [ ]:
date1 <- as.Date("2012-06-28")

In [ ]:
date1

[1] "2012-06-28"

In [ ]:
class(date1)

[1] "Date"

In [ ]:
as.numeric(date1)

[1] 15519

In [ ]:
date_1970 <- as.Date("1970-01-01")

In [ ]:
as.numeric(date_1970)

[1] 1

numeric: calculate how many days after '1970-01-01'

In [ ]:
date2 <- as.POSIXct("2012-06-28 17:42")
date2

[1] "2012-06-28 17:42:00 UTC"

In [ ]:
class(date2)

[1] "POSIXct" "POSIXt"

In [ ]:
as.numeric(date2) # seconds

[1] 1340905320

In [ ]:
date3 <- as.POSIXct("1970-01-01 00:00:00")
date3

[1] "1970-01-01 UTC"

In [ ]:
as.numeric(date3)

[1] 0

In [ ]:
class(as.numeric(date3))

[1] "numeric"

#### 1.3.4 Logical

Logicals are a way of representing data that can be either TRUE or FALSE. Numerically , **TRUE is the same as 1 and FALSE is the same as 0.**

In [ ]:
# TRUE = 1
TRUE - 1

[1] 0

In [ ]:
# FALSE = 0
FALSE + 1

[1] 1

In [ ]:
TRUE * 3

[1] 3

In [ ]:
FALSE * 3

[1] 0

In [ ]:
FALSE * 3 + TRUE * 2

[1] 2

In [ ]:
k <- TRUE
k

[1] TRUE

In [ ]:
class(k)

[1] "logical"

In [ ]:
is.logical(k)

[1] TRUE

In [ ]:
is.factor(k)

[1] FALSE

In [ ]:
T # T A

[1] TRUE

In [ ]:
F

[1] FALSE

Logicals can result from comparing two numbers, or characters.

In [ ]:
2 == 3

[1] FALSE

In [ ]:
2 != 3

[1] TRUE

In [ ]:
2 < 3

[1] TRUE

In [ ]:
2 > 3

[1] FALSE

In [ ]:
2 >= 3

[1] FALSE

In [ ]:
"data" == "data"

[1] TRUE

### 1.4 Vectors

A vector is a collection of elements, all of the same type. For instance, c(1, 3, 2, 1, 5) is a vector
consisting of the numbers 1, 3, 2, 1, 5, in that order. Similarly , c(“R”
“Excel”
“SAS”
,
,
,
“Excel”) is a vector of the character elements,
“R”
“Excel”
“SAS”
,
,
, and “Excel”
. A vector
cannot be of mixed type.

# element: int, character, logcial, etc.

In [ ]:
x <-c (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
x

[1]  1  2  3  4  5  6  7  8  9 10

#### 1.4.1 Vector Operations

In [ ]:
x * 3

[1]  3  6  9 12 15 18 21 24 27 30

In [ ]:
x + 2

[1]  3  4  5  6  7  8  9 10 11 12

In [ ]:
x - 3

[1] -2 -1  0  1  2  3  4  5  6  7

In [ ]:
x / 4

[1] 0.25 0.50 0.75 1.00 1.25 1.50 1.75 2.00 2.25 2.50

In [ ]:
x^2

[1]   1   4   9  16  25  36  49  64  81 100

In [ ]:
sqrt(x)

[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

Earlier we created a vector of the first ten numbers using the c function, which creates a vector. A
shortcut is the : operator, which generates a sequence of consecutive numbers, in either direction.

In [ ]:
1 :10 # (value_from : value_to)

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
2 : 6 # step: 1

[1] 2 3 4 5 6

In [ ]:
10:1 # step: -1

[1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
-2:3

[1] -2 -1  0  1  2  3

In [ ]:
5:-7

[1]  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7

In [ ]:
x <- 1:5
x

[1] 1 2 3 4 5

In [ ]:
y <- 10:14
y

[1] 10 11 12 13 14

In [ ]:
x + y

[1] 11 13 15 17 19

In [ ]:
x - y

[1] -9 -9 -9 -9 -9

In [ ]:
x * y

[1] 10 22 36 52 70

In [ ]:
x / y

[1] 0.1000000 0.1818182 0.2500000 0.3076923 0.3571429

In [ ]:
x^y

[1]          1       2048     531441   67108864 6103515625

In [ ]:
length(x) # how many elements in the vector

[1] 5

In [ ]:
length(y)

[1] 5

In [ ]:
x + y

[1] 11 13 15 17 19

In [ ]:
1 : 10

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
length((1 : 10))

[1] 10

In [ ]:
x

[1] 1 2 3 4 5

In [ ]:
c(1, 2)

[1] 1 2

1 + 1 = 2, 2 + 2 = 4, 3 + 1 = 4, 4 + 2 = 6, 5 + 1 = 6

In [ ]:
x + c(1, 2)

Warning message in x + c(1, 2):
“longer object length is not a multiple of shorter object length”


[1] 2 4 4 6 6

In [ ]:
x + c(1, 2, 3, 4, 5)

[1]  2  4  6  8 10

In [ ]:
x

[1] 1 2 3 4 5

In [ ]:
x <= 5

[1] TRUE TRUE TRUE TRUE TRUE

In [ ]:
x > y

[1] FALSE FALSE FALSE FALSE FALSE

In [ ]:
x < y

[1] TRUE TRUE TRUE TRUE TRUE

In [ ]:
x <- 10:1
y <- -4:5

In [ ]:
x

[1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
y

[1] -4 -3 -2 -1  0  1  2  3  4  5

To test whether all the resulting elements are TRUE, use the all function. Similarly , the any function
checks whether any element is TRUE.

In [ ]:
any(x < y) # if there is at least one element < elements in y

[1] TRUE

In [ ]:
all(x < y) # if all elements in x are < elements in y

[1] FALSE

In [ ]:
name <- c("Alice", "Bob", "Chris", "Dora")
name

[1] "Alice" "Bob"   "Chris" "Dora"

In [ ]:
nchar(name) # the length of each element

[1] 5 3 5 4

In [ ]:
z <- 5: 15
z

[1]  5  6  7  8  9 10 11 12 13 14 15

In [ ]:
nchar(z)

[1] 1 1 1 1 1 2 2 2 2 2 2

In [ ]:
z

[1]  5  6  7  8  9 10 11 12 13 14 15

In [ ]:
z[4] # vector_var[index] index >= 1

[1] 8

In [ ]:
z[1:3] # val-x : val-y  --> FROM val-x TO val-y

[1] 5 6 7

In [ ]:
z[3:5]

[1] 7 8 9

In [ ]:
z[c(2, 4, 6)]

[1]  6  8 10

In [ ]:
n <- c(One="a", Two="y", Last="r") # key: val , 3 elements, 3 pairs of key:val
n

One  Two Last 
 "a"  "y"  "r"

In [ ]:
n[3]

Last 
 "r"

In [ ]:
w <- 1:3

In [ ]:
w

[1] 1 2 3

In [ ]:
c("a", "b", "c")

[1] "a" "b" "c"

In [ ]:
names(w) <- c("a", "b", "c")

In [ ]:
names(w)

[1] "a" "b" "c"

In [ ]:
w

In [ ]:
names(w) <-c("one", "two", "three")

In [ ]:
w

In [ ]:
names(w)

[1] "one"   "two"   "three"

In [ ]:
w <- c(11, 22, 33)

In [ ]:
w

[1] 11 22 33

In [ ]:
names(w) <-c("one", "two", "three")

In [ ]:
names(w) # variable

[1] "one"   "two"   "three"

In [ ]:
names_w <- c("one", "two", "three")
names_w

[1] "one"   "two"   "three"

#### 1.4.2 Factor Vectors

Factors are an important concept in R, especially when building models. Let’s create a simple
vector of text data that has a few repeats.

In [ ]:
q <- c(1, 2, 3)

In [ ]:
q

[1] 1 2 3

In [ ]:
q2 <-c(q, "apple", "apple", "banana","lemon", "lemon", "banana", TRUE, FALSE)

In [ ]:
q2

[1] "1"      "2"      "3"      "apple"  "apple"  "banana" "lemon"  "lemon" 
 [9] "banana" "TRUE"   "FALSE"

In [ ]:
q2Factor <- as.factor(q2)

In [ ]:
q2Factor

[1] 1      2      3      apple  apple  banana lemon  lemon  banana TRUE  
[11] FALSE 
Levels: 1 2 3 apple banana FALSE lemon TRUE

In [ ]:
class(q2Factor)

[1] "factor"

In [ ]:
as.numeric(q2Factor)
# 1 2 3 apple(4) apple(4) banana(5) lemon(7) lemon(7) banana(5) TRUE(8) FALSE(6)

[1] 1 2 3 4 4 5 7 7 5 8 6

In [ ]:
factor(x=c("High School", "College", "Masters", "Doctorate", "High School"), levels=c("High School", "College", "Masters", "Doctorate"), ordered=TRUE)

[1] High School College     Masters     Doctorate   High School
Levels: High School < College < Masters < Doctorate

In [ ]:
factor(x=c("Doctorate", "College", "High School", "Masters"), levels=c("High School", "College", "Masters", "Doctorate"), ordered=TRUE)

[1] Doctorate   College     High School Masters    
Levels: High School < College < Masters < Doctorate

### 1.5 Calling Functions

In [ ]:
x <- 2: 6
x

[1] 2 3 4 5 6

In [ ]:
mean(x)

[1] 4

In [ ]:
max(x)

[1] 6

In [ ]:
min(x)

[1] 2

In [ ]:
median(x)

[1] 4

### 1.6 Function Documentation


To get help on binary operators like +,
* or == surround them with back ticks (`)

In [ ]:
?`+`

In [ ]:
?`==`

There are occasions when we have only a sense of the function we want to use. In that case we can
look up the function by using part of the name with **apropos**.

In [ ]:
apropos("mea")

[1] ".colMeans"          ".rowMeans"          "colMeans"          
 [4] "influence.measures" "kmeans"             "mean"              
 [7] "mean.Date"          "mean.default"       "mean.difftime"     
[10] "mean.POSIXct"       "mean.POSIXlt"       "rowMeans"          
[13] "weighted.mean"

### 1.7 Missing Data


Missing data plays a critical role in both statistics and computing, and R has two types of missing data,
**NA** and **NULL**. While they are similar, they behave differently and that difference needs attention.

#### 1.7.1 NA

In [ ]:
zChar <- c("Tiger", NA, "Lion", NA)
zChar

[1] "Tiger" NA      "Lion"  NA

In [ ]:
is.na(zChar)

[1] FALSE  TRUE FALSE  TRUE

In [ ]:
z <- c(1, 2, NA, 8, 3, NA, 3)
z

[1]  1  2 NA  8  3 NA  3

In [ ]:
is.na(z)

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE

If we calculate the mean of z, the answer will be NA since mean returns NA if even a single element is
NA.

In [ ]:
mean(z)

[1] NA

When the na.rm is TRUE, mean first removes the missing data, then calculates the mean.

# na.rm means remove NA values from dataset

In [ ]:
mean(z, na.rm=TRUE)
# mean(1 + 2 + 8 + 3 + 3)

[1] 3.4

In [ ]:
# sum, min, max, var, sd
sum(z)

[1] NA

In [ ]:
sum(z, na.rm = TRUE)

[1] 17

#### 1.7.2 NULL

NULL is the absence of anything. It is not exactly missingness, it is nothingness. Functions can sometimes
return NULL and their arguments can be NULL. An important difference between NA and NULL is that
NULL is atomical and cannot exist within a vector. If used inside a vector, it simply disappears.

In [ ]:
z <- c(1, NULL,3)
z

[1] 1 3

In [ ]:
d <- NULL

In [ ]:
is.null(d)

[1] TRUE

In [ ]:
is.null(7)

[1] FALSE

### 1.8 Pipes

The pipe from the magrittr package works by
taking the value or object on the left-hand side of the pipe and inserting it into the first argument of the
function that is on the right-hand side of the pipe. A simple example example would be using a pipe to
feed x to the mean function.

In [ ]:
library(magrittr)

In [ ]:
x <- 1:10
x

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
mean(x)

[1] 5.5

# %>%

In [ ]:
x %>% mean # from left to right

[1] 5.5

In [ ]:
z <- c(1, 2, NA, 8, 3, NA, 3)
z

[1]  1  2 NA  8  3 NA  3

In [ ]:
sum(is.na(z))

[1] 2

In [ ]:
z %>% is.na %>% sum

[1] 2

In [ ]:
z %>% mean(na.rm=TRUE)

[1] 3.4

## 2 Advanced Data Structures


Sometimes data require more complex storage than simple vectors and thankfully R provides a host of
data structures. The most common are the data.frame, matrix and list, followed by the array.
Of these, the data.frame will be most familiar to anyone who has used a spreadsheet, the matrix to
people familiar with matrix math and the list to programmers.

### 2.1 data.frames


On the surface a data.frame is just like an Excel spreadsheet in that it has columns and rows. In
statistical terms, each column is a variable and each row is an observation.

There are numerous ways to construct a data.frame, the simplest being to use the data.frame
function.

In [40]:
x <- 10:1
x

[1] 10  9  8  7  6  5  4  3  2  1

In [41]:
y <- -4:5
y

[1] -4 -3 -2 -1  0  1  2  3  4  5

In [42]:
q <- c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten")
q

[1] "one"   "two"   "three" "four"  "five"  "six"   "seven" "eight" "nine" 
[10] "ten"

In [43]:
theDF <- data.frame(x, y, q)

In [44]:
theDF

x  y  q    
1  10 -4 one  
2   9 -3 two  
3   8 -2 three
4   7 -1 four 
5   6  0 five 
6   5  1 six  
7   4  2 seven
8   3  3 eight
9   2  4 nine 
10  1  5 ten

In [ ]:
theDF <- data.frame(First=x, Second=y, Number=q)

In [ ]:
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
nrow(theDF)

[1] 10

In [ ]:
ncol(theDF)

[1] 3

In [ ]:
dim(theDF)

[1] 10  3

In [ ]:
names(theDF)

[1] "First"  "Second" "Number"

In [ ]:
names(theDF)[2]

[1] "Second"

In [ ]:
rownames(theDF) # index starts with 1

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
rownames(theDF) <- c("#1", "#2", "#3", "#4", "#5", "#6", "#7", "#8", "#9", "#10")

In [ ]:
theDF

First Second Number
#1  10    -4     one   
#2   9    -3     two   
#3   8    -2     three 
#4   7    -1     four  
#5   6     0     five  
#6   5     1     six   
#7   4     2     seven 
#8   3     3     eight 
#9   2     4     nine  
#10  1     5     ten

In [ ]:
rownames(theDF) <- NULL
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
rownames(theDF)

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
head(theDF)

First Second Number
1 10    -4     one   
2  9    -3     two   
3  8    -2     three 
4  7    -1     four  
5  6     0     five  
6  5     1     six

In [ ]:
head(theDF, n=3)

First Second Number
1 10    -4     one   
2  9    -3     two   
3  8    -2     three

In [ ]:
tail(theDF, n=1)

First Second Number
10 1     5      ten

In [ ]:
class(theDF)

[1] "data.frame"

Like many other aspects of R, there are multiple ways to access an individual
column. There is the $ operator and also the square brackets.

In [ ]:
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
theDF[5, 1:2]

First Second
5 6     0

$

In [ ]:
theDF$Number

[1] "one"   "two"   "three" "four"  "five"  "six"   "seven" "eight" "nine" 
[10] "ten"

In [ ]:
theDF[10, 3] # 1st: row index, 2nd: col index

[1] "ten"

In [ ]:
theDF[3, 2:3] # 2nd: 2:3 the col index is from 2 to 3

Second Number
3 -2     three

In [ ]:
c(3, 5)

[1] 3 5

In [ ]:
theDF[c(3, 5), 2] # 1st: c(3, 5) row index

[1] -2  0

In [ ]:
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
theDF[c(1, 3, 5, 7, 9), 3]

[1] "one"   "three" "five"  "seven" "nine"

In [ ]:
c(2, 5)

[1] 2 5

In [ ]:
2 : 5 # from 2 to 3, step 1

[1] 2 3 4 5

In [ ]:
theDF[c(3, 5), 2:3] # rows 3 and 5, columns 2 through 3

Second Number
3 -2     three 
5  0     five

In [ ]:
theDF[, 3] # treat the empty param 1st as all

[1] "one"   "two"   "three" "four"  "five"  "six"   "seven" "eight" "nine" 
[10] "ten"

In [ ]:
theDF[, 2:3]

Second Number
1  -4     one   
2  -3     two   
3  -2     three 
4  -1     four  
5   0     five  
6   1     six   
7   2     seven 
8   3     eight 
9   4     nine  
10  5     ten

In [ ]:
theDF[2, ]

First Second Number
2 9     -3     two

In [ ]:
theDF[2:4, ]

First Second Number
2 9     -3     two   
3 8     -2     three 
4 7     -1     four

In [ ]:
class(c("First","Number"))

[1] "character"

In [ ]:
theDF[2, c("First","Second", "Number")]

First Second Number
2 9     -3     two

In [ ]:
theDF[,"First"]

[1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
class(theDF[,"First"])

[1] "integer"

In [ ]:
theDF["Number"]

Number
1  one   
2  two   
3  three 
4  four  
5  five  
6  six   
7  seven 
8  eight 
9  nine  
10 ten

In [ ]:
theDF["Number"]

Number
1  one   
2  two   
3  three 
4  four  
5  five  
6  six   
7  seven 
8  eight 
9  nine  
10 ten

In [ ]:
class(theDF["Number"])

[1] "data.frame"

In [ ]:
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
theDF["Number"]

Number
1  one   
2  two   
3  three 
4  four  
5  five  
6  six   
7  seven 
8  eight 
9  nine  
10 ten

In [ ]:
theDF[["Number"]]

[1] "one"   "two"   "three" "four"  "five"  "six"   "seven" "eight" "nine" 
[10] "ten"

In [ ]:
theDF["Number"]

Number
1  one   
2  two   
3  three 
4  four  
5  five  
6  six   
7  seven 
8  eight 
9  nine  
10 ten

In [ ]:
class(theDF[["Number"]])

[1] "character"

In [ ]:
theDF[,"Number", drop=FALSE]

Number
1  one   
2  two   
3  three 
4  four  
5  five  
6  six   
7  seven 
8  eight 
9  nine  
10 ten

In [ ]:
class(theDF[,"Number", drop=FALSE])

[1] "data.frame"

In [ ]:
theDF

First Second Number
1  10    -4     one   
2   9    -3     two   
3   8    -2     three 
4   7    -1     four  
5   6     0     five  
6   5     1     six   
7   4     2     seven 
8   3     3     eight 
9   2     4     nine  
10  1     5     ten

In [ ]:
theDF[1, 3, drop=TRUE]

[1] "one"

theDF[,
"Sport"
, drop=FALSE]

### 2.2 Lists

Often a container is needed to hold arbitrary objects of either the same type or varying types. R
accomplishes this through lists. They store any number of items of any type. A list can contain all
numerics or characters or a mix of the two or data.frames or, recursively , other lists.z

In [1]:
list(1, 2, 3, 99, 1000)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 99

[[5]]
[1] 1000

In [8]:
list(c(1, 2, 3), c(88, 99, 77))

[[1]]
[1] 1 2 3

[[2]]
[1] 88 99 77

In [9]:
list(c(1, 2, 3), 3:7)

[[1]]
[1] 1 2 3

[[2]]
[1] 3 4 5 6 7

In [10]:
(list3 <- list(c(1, 2, 3), 3:7))

[[1]]
[1] 1 2 3

[[2]]
[1] 3 4 5 6 7

In [11]:
list3

[[1]]
[1] 1 2 3

[[2]]
[1] 3 4 5 6 7

In [12]:
theDF

x  y  q    
1  10 -4 one  
2   9 -3 two  
3   8 -2 three
4   7 -1 four 
5   6  0 five 
6   5  1 six  
7   4  2 seven
8   3  3 eight
9   2  4 nine 
10  1  5 ten

In [13]:
list(theDF, 1:10, "Apple", c(999, 1000))

[[1]]
    x  y     q
1  10 -4   one
2   9 -3   two
3   8 -2 three
4   7 -1  four
5   6  0  five
6   5  1   six
7   4  2 seven
8   3  3 eight
9   2  4  nine
10  1  5   ten

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[3]]
[1] "Apple"

[[4]]
[1]  999 1000

In [45]:
list5 <- list(theDF, 1:10, list3)

In [46]:
list5

[[1]]
    x  y     q
1  10 -4   one
2   9 -3   two
3   8 -2 three
4   7 -1  four
5   6  0  five
6   5  1   six
7   4  2 seven
8   3  3 eight
9   2  4  nine
10  1  5   ten

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[3]]
[[3]][[1]]
[1] 1 2 3

[[3]][[2]]
[1] 3 4 5 6 7

In [16]:
names(list5)

NULL

In [49]:
names(list5) <-c("data.frame", "vector", "list")
names(list5)

[1] "data.frame" "vector"     "list"

In [18]:
list6 <- list(TheDataFrame=theDF, TheVector=1:10, TheList=list3)
list6

$TheDataFrame
    x  y     q
1  10 -4   one
2   9 -3   two
3   8 -2 three
4   7 -1  four
5   6  0  five
6   5  1   six
7   4  2 seven
8   3  3 eight
9   2  4  nine
10  1  5   ten

$TheVector
 [1]  1  2  3  4  5  6  7  8  9 10

$TheList
$TheList[[1]]
[1] 1 2 3

$TheList[[2]]
[1] 3 4 5 6 7

In [19]:
names(list6)

[1] "TheDataFrame" "TheVector"    "TheList"

In [20]:
(emptyList <- vector(mode="list", length=4))

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

In [50]:
theDF

x  y  q    
1  10 -4 one  
2   9 -3 two  
3   8 -2 three
4   7 -1 four 
5   6  0 five 
6   5  1 six  
7   4  2 seven
8   3  3 eight
9   2  4 nine 
10  1  5 ten

In [51]:
list5

$data.frame
    x  y     q
1  10 -4   one
2   9 -3   two
3   8 -2 three
4   7 -1  four
5   6  0  five
6   5  1   six
7   4  2 seven
8   3  3 eight
9   2  4  nine
10  1  5   ten

$vector
 [1]  1  2  3  4  5  6  7  8  9 10

$list
$list[[1]]
[1] 1 2 3

$list[[2]]
[1] 3 4 5 6 7

In [52]:
list5[[3]]

[[1]]
[1] 1 2 3

[[2]]
[1] 3 4 5 6 7

In [53]:
list5[["vector"]]

[1]  1  2  3  4  5  6  7  8  9 10

## $

In [54]:
list5[[1]]

x  y  q    
1  10 -4 one  
2   9 -3 two  
3   8 -2 three
4   7 -1 four 
5   6  0 five 
6   5  1 six  
7   4  2 seven
8   3  3 eight
9   2  4 nine 
10  1  5 ten

In [56]:
list5[[1]][,2, drop=TRUE]

[1] -4 -3 -2 -1  0  1  2  3  4  5

- **drop = TRUE (Default)**: If the subset operation results in a single row or a single column, R will "drop" the dimension, returning a vector instead of a data frame or matrix.

- **drop = FALSE:** R will preserve the original dimensions, even if the result is a single row or column. It will return a data frame (for data frames) or a matrix (for matrices) with one row or one column.

In [33]:
length(list5)

[1] 3

In [34]:
list5[[4]] <- 2

In [35]:
length(list5)

[1] 4

In [36]:
list5[["NewElement"]] <- 3:6

In [37]:
list5

$data.frame
    x  y     q
1  10 -4   one
2   9 -3   two
3   8 -2 three
4   7 -1  four
5   6  0  five
6   5  1   six
7   4  2 seven
8   3  3 eight
9   2  4  nine
10  1  5   ten

$vector
 [1]  1  2  3  4  5  6  7  8  9 10

$list
$list[[1]]
[1] 1 2 3

$list[[2]]
[1] 3 4 5 6 7


[[4]]
[1] 2

$NewElement
[1] 3 4 5 6

In [38]:
length(list5)

[1] 5

In [39]:
names(list5)

[1] "data.frame" "vector"     "list"       ""           "NewElement"

### 2.3 Matrices


A very common mathematical structure that is essential to statistics is a matrix. This is similar to a
data.frame in that it is rectangular with rows and columns except that every single element,
regardless of column, must be the same type, most commonly all numerics.

In [57]:
# create a 5x2 matrix
A <- matrix(1:10, nrow=5)

In [58]:
A

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [59]:
# create another 5x2 matrix
B <- matrix(21:30, nrow=5)


In [60]:
B

[,1] [,2]
[1,] 21   26  
[2,] 22   27  
[3,] 23   28  
[4,] 24   29  
[5,] 25   30

In [63]:
# create another 2x10 matrix
C <- matrix(21:40, nrow=2)

In [64]:
C

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 21   23   25   27   29   31   33   35   37   39   
[2,] 22   24   26   28   30   32   34   36   38   40

In [67]:
nrow(B)

[1] 5

In [68]:
ncol(B)

[1] 2

In [69]:
dim(A)

[1] 5 2

In [70]:
1 * 2

[1] 2

In [71]:
A * B

[,1] [,2]
[1,]  21  156 
[2,]  44  189 
[3,]  69  224 
[4,]  96  261 
[5,] 125  300

In [73]:
A

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [74]:
B

[,1] [,2]
[1,] 21   26  
[2,] 22   27  
[3,] 23   28  
[4,] 24   29  
[5,] 25   30

In [78]:
E <- matrix(21:30, nrow=5) # 21:30

In [79]:
E

[,1] [,2]
[1,] 21   26  
[2,] 22   27  
[3,] 23   28  
[4,] 24   29  
[5,] 25   30

In [80]:
E == B

[,1] [,2]
[1,] TRUE TRUE
[2,] TRUE TRUE
[3,] TRUE TRUE
[4,] TRUE TRUE
[5,] TRUE TRUE

Matrix multiplication is a commonly used operation in mathematics, requiring the number of columns
of the left-hand matrix to be the same as the number of rows of the right-hand matrix. Both A and B
are 5X2 so we will transpose B so it can be used on the right-hand side.

In [82]:
B

[,1] [,2]
[1,] 21   26  
[2,] 22   27  
[3,] 23   28  
[4,] 24   29  
[5,] 25   30

In [ ]:
5 rows x 2 cols # t(B) --> 2 rows v 5 cols

In [81]:
A %*% t(B)

[,1] [,2] [,3] [,4] [,5]
[1,] 177  184  191  198  205 
[2,] 224  233  242  251  260 
[3,] 271  282  293  304  315 
[4,] 318  331  344  357  370 
[5,] 365  380  395  410  425

In [87]:
colnames(A)

[1] "Left"  "Right"

In [88]:
rownames(A)

[1] "1st" "2nd" "3rd" "4th" "5th"

In [85]:
colnames(A) <- c("Left", "Right")

In [86]:
rownames(A) <- c("1st", "2nd","3rd","4th","5th")

In [93]:
colnames(B)

[1] "First"  "Second"

In [94]:
rownames(B)

[1] "One"   "Two"   "Three" "Four"  "Five"

In [91]:
colnames(B) <- c("First", "Second")

In [92]:
rownames(B) <- c("One","Two","Three","Four","Five")

In [100]:
colnames(C)

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J"

In [98]:
rownames(C)

[1] "Top"    "Bottom"

In [103]:
LETTERS[1:26]

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [99]:
colnames(C) <- LETTERS[1:10]

In [97]:
rownames(C) <- c("Top","Bottom")

In [104]:
A

Left Right
1st 1     6   
2nd 2     7   
3rd 3     8   
4th 4     9   
5th 5    10

Notice the effect when transposing a matrix and multiplying matrices. Transposing naturally flips
the row and column names. Matrix multiplication keeps the row names from the left matrix and the
column names from the right matrix.

In [105]:
t(A)

1st 2nd 3rd 4th 5th
Left  1   2   3   4    5 
Right 6   7   8   9   10

In [106]:
C

A  B  C  D  E  F  G  H  I  J 
Top    21 23 25 27 29 31 33 35 37 39
Bottom 22 24 26 28 30 32 34 36 38 40

In [107]:
A %*% C

A   B   C   D   E   F   G   H   I   J  
1st 153 167 181 195 209 223 237 251 265 279
2nd 196 214 232 250 268 286 304 322 340 358
3rd 239 261 283 305 327 349 371 393 415 437
4th 282 308 334 360 386 412 438 464 490 516
5th 325 355 385 415 445 475 505 535 565 595

### 2.4 Arrays


An array is essentially a multidimensional vector. It must all be of the same type, and individual
elements are accessed in a similar fashion using square brackets. The first element is the row index, the
second is the column index and the remaining elements are for outer dimensions.

In [111]:
theArray <- array(1:12, dim=c(2, 3, 2)) # 2d 3d

In [112]:
theArray

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

# 1, 2, 3,  4, 5, 6, 7, 8, 9, 10, 11, 12

# dim_1: 2
[[], []]
# dim_2: 3
[[[], []], [[], []], [[], []]]
# dim_3: 2
[[[[], []], [[], []], [[], []]], [[[], []], [[], []], [[], []]]]

[[[1][2]][[3][4]][[5][6]]], [[[7][8]][[9][10]][[11][12]]]

In [114]:
theArray[1, , 1]

[1] 1 3 5

In [115]:
theArray[, , 1] # empty: return all values for that dim, val: return a target value in that index

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## 3 Reading Data into R


### 3.1 Reading CSVs


In [116]:
theUrl <- "http://www.jaredlander.com/data/TomatoFirst.csv"
tomato <-read.table(file=theUrl, header=TRUE, sep=",")

In [117]:
tomato

Round Tomato                   Price Source           Sweet Acid Color
1  1     Simpson SM                3.99 Whole Foods      2.8   2.8  3.7  
2  1     Tuttorosso (blue)         2.99 Pioneer          3.3   2.8  3.4  
3  1     Tuttorosso (green)        0.99 Pioneer          2.8   2.6  3.3  
4  1     La Fede SM DOP            3.99 Shop Rite        2.6   2.8  3.0  
5  2     Cento SM DOP              5.49 D Agostino       3.3   3.1  2.9  
6  2     Cento Organic             4.99 D Agostino       3.2   2.9  2.9  
7  2     La Valle SM               3.99 Shop Rite        2.6   2.8  3.6  
8  2     La Valle SM DOP           3.99 Faicos           2.1   2.7  3.1  
9  3     Stanislaus Alta Cucina    4.53 Restaurant Depot 3.4   3.3  4.1  
10 3     Ciao                        NA Other            2.6   2.9  3.4  
11 3     Scotts Backyard SM        0.00 Home Grown       1.6   2.9  3.1  
12 3     Di Casa Barone (organic) 12.80 Eataly           1.7   3.6  3.8  
13 4     Trader Joes Plum          1.49 Trader Joes      3.4   3.3  4.0  
14 4     365 Whole Foods           1.49 Whole Foods      2.8   2.7  3.4  
15 4     Muir Glen Organic         3.19 Whole Foods      2.9   2.8  2.7  
16 4     Bionature Organic         3.39 Whole Foods      2.4   3.3  3.4  
   Texture Overall Avg.of.Totals Total.of.Avg
1  3.4     3.4     16.1          16.1        
2  3.0     2.9     15.3          15.3        
3  2.8     2.9     14.3          14.3        
4  2.3     2.8     13.4          13.4        
5  2.8     3.1     14.4          15.2        
6  3.1     2.9     15.5          15.1        
7  3.4     2.6     14.7          14.9        
8  2.4     2.2     12.6          12.5        
9  3.2     3.7     17.8          17.7        
10 3.3     2.9     15.3          15.2        
11 2.4     1.9     11.9          11.9        
12 2.3     1.4     12.7          12.7        
13 3.6     3.9     17.8          18.2        
14 3.1     3.1     14.8          15.2        
15 3.2     3.1     14.8          14.7        
16 3.2     2.8     15.1          15.2

In [118]:
library(data.table)

In [121]:
theUrl <- "http://www.jaredlander.com/data/TomatoFirst.csv"
tomato3 <-fread(input=theUrl, sep=',',, header=TRUE)

In [122]:
head(tomato3)

Round Tomato             Price Source      Sweet Acid Color Texture Overall
1 1     Simpson SM         3.99  Whole Foods 2.8   2.8  3.7   3.4     3.4    
2 1     Tuttorosso (blue)  2.99  Pioneer     3.3   2.8  3.4   3.0     2.9    
3 1     Tuttorosso (green) 0.99  Pioneer     2.8   2.6  3.3   2.8     2.9    
4 1     La Fede SM DOP     3.99  Shop Rite   2.6   2.8  3.0   2.3     2.8    
5 2     Cento SM DOP       5.49  D Agostino  3.3   3.1  2.9   2.8     3.1    
6 2     Cento Organic      4.99  D Agostino  3.2   2.9  2.9   3.1     2.9    
  Avg of Totals Total of Avg
1 16.1          16.1        
2 15.3          15.3        
3 14.3          14.3        
4 13.4          13.4        
5 14.4          15.2        
6 15.5          15.1

### 3.2 Excel Data


In [123]:
download.file(url='http://www.jaredlander.com/data/ExcelExample.xlsx', destfile='/content/sample_data/ExcelExample.xlsx', method='auto')

In [124]:
library(readxl)

In [125]:
excel_sheets('/content/sample_data/ExcelExample.xlsx')

[1] "Tomato" "Wine"   "ACS"

In [130]:
tomatoXL <-read_excel('/content/sample_data/ExcelExample.xlsx', sheet=1)

In [131]:
tomatoXL

Round Tomato                   Price Source           Sweet Acid Color
1  1     Simpson SM                3.99 Whole Foods      2.8   2.8  3.7  
2  1     Tuttorosso (blue)         2.99 Pioneer          3.3   2.8  3.4  
3  1     Tuttorosso (green)        0.99 Pioneer          2.8   2.6  3.3  
4  1     La Fede SM DOP            3.99 Shop Rite        2.6   2.8  3.0  
5  2     Cento SM DOP              5.49 D Agostino       3.3   3.1  2.9  
6  2     Cento Organic             4.99 D Agostino       3.2   2.9  2.9  
7  2     La Valle SM               3.99 Shop Rite        2.6   2.8  3.6  
8  2     La Valle SM DOP           3.99 Faicos           2.1   2.7  3.1  
9  3     Stanislaus Alta Cucina    4.53 Restaurant Depot 3.4   3.3  4.1  
10 3     Ciao                        NA Other            2.6   2.9  3.4  
11 3     Scotts Backyard SM        0.00 Home Grown       1.6   2.9  3.1  
12 3     Di Casa Barone (organic) 12.80 Eataly           1.7   3.6  3.8  
13 4     Trader Joes Plum          1.49 Trader Joes      3.4   3.3  4.0  
14 4     365 Whole Foods           1.49 Whole Foods      2.8   2.7  3.4  
15 4     Muir Glen Organic         3.19 Whole Foods      2.9   2.8  2.7  
16 4     Bionature Organic         3.39 Whole Foods      2.4   3.3  3.4  
   Texture Overall Avg of Totals Total of Avg
1  3.4     3.4     16.1          16.1        
2  3.0     2.9     15.3          15.3        
3  2.8     2.9     14.3          14.3        
4  2.3     2.8     13.4          13.4        
5  2.8     3.1     14.4          15.2        
6  3.1     2.9     15.5          15.1        
7  3.4     2.6     14.7          14.9        
8  2.4     2.2     12.6          12.5        
9  3.2     3.7     17.8          17.7        
10 3.3     2.9     15.3          15.2        
11 2.4     1.9     11.9          11.9        
12 2.3     1.4     12.7          12.7        
13 3.6     3.9     17.8          18.2        
14 3.1     3.1     14.8          15.2        
15 3.2     3.1     14.8          14.7        
16 3.2     2.8     15.1          15.2

In [128]:
wineXL1 <- read_excel('/content/sample_data/ExcelExample.xlsx', sheet=2)

In [129]:
head(wineXL1)

Cultivar Alcohol Malic acid Ash  Alcalinity of ash Magnesium Total phenols
1 1        14.23   1.71       2.43 15.6              127       2.80         
2 1        13.20   1.78       2.14 11.2              100       2.65         
3 1        13.16   2.36       2.67 18.6              101       2.80         
4 1        14.37   1.95       2.50 16.8              113       3.85         
5 1        13.24   2.59       2.87 21.0              118       2.80         
6 1        14.20   1.76       2.45 15.2              112       3.27         
  Flavanoids Nonflavanoid phenols Proanthocyanins Color intensity Hue 
1 3.06       0.28                 2.29            5.64            1.04
2 2.76       0.26                 1.28            4.38            1.05
3 3.24       0.30                 2.81            5.68            1.03
4 3.49       0.24                 2.18            7.80            0.86
5 2.69       0.39                 1.82            4.32            1.04
6 3.39       0.34                 1.97            6.75            1.05
  OD280/OD315 of diluted wines Proline
1 3.92                         1065   
2 3.40                         1050   
3 3.17                         1185   
4 3.45                         1480   
5 2.93                          735   
6 2.85                         1450

In [132]:
wineXL1 <- read_excel('/content/sample_data/ExcelExample.xlsx', sheet='Wine')

In [133]:
head(wineXL1)

Cultivar Alcohol Malic acid Ash  Alcalinity of ash Magnesium Total phenols
1 1        14.23   1.71       2.43 15.6              127       2.80         
2 1        13.20   1.78       2.14 11.2              100       2.65         
3 1        13.16   2.36       2.67 18.6              101       2.80         
4 1        14.37   1.95       2.50 16.8              113       3.85         
5 1        13.24   2.59       2.87 21.0              118       2.80         
6 1        14.20   1.76       2.45 15.2              112       3.27         
  Flavanoids Nonflavanoid phenols Proanthocyanins Color intensity Hue 
1 3.06       0.28                 2.29            5.64            1.04
2 2.76       0.26                 1.28            4.38            1.05
3 3.24       0.30                 2.81            5.68            1.03
4 3.49       0.24                 2.18            7.80            0.86
5 2.69       0.39                 1.82            4.32            1.04
6 3.39       0.34                 1.97            6.75            1.05
  OD280/OD315 of diluted wines Proline
1 3.92                         1065   
2 3.40                         1050   
3 3.17                         1185   
4 3.45                         1480   
5 2.93                          735   
6 2.85                         1450

### 3.3 Reading from Databases


In [134]:
install.packages('RSQLite') # DB: SQL SEVER, ORACLE, RSQLite

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘plogr’




In [135]:
library(RSQLite)

In [136]:
download.file("http://www.jaredlander.com/data/diamonds.db",destfile = "/content/sample_data/diamonds.db", mode='wb')

In [137]:
drv <- dbDriver('SQLite')

In [138]:
class(drv)

[1] "SQLiteDriver"
attr(,"package")
[1] "RSQLite"

In [139]:
con <- dbConnect(drv,'/content/sample_data/diamonds.db')

In [140]:
class(con)

[1] "SQLiteConnection"
attr(,"package")
[1] "RSQLite"

In [141]:
dbListTables(con)

[1] "DiamondColors" "diamonds"      "sqlite_stat1"

In [142]:
dbListFields(con, name='diamonds')

[1] "carat"   "cut"     "color"   "clarity" "depth"   "table"   "price"  
 [8] "x"       "y"       "z"

In [143]:
dbListFields(con, name='DiamondColors')

[1] "Color"       "Description" "Details"

In [144]:
diamondsTable <- dbGetQuery(con,"SELECT * FROM diamonds",stringsAsFactors=FALSE)

In [145]:
diamondsTable

carat cut       color clarity depth table price x    y    z   
1     0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2     0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3     0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4     0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5     0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6     0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48
7     0.24  Very Good I     VVS1    62.3  57    336   3.95 3.98 2.47
8     0.26  Very Good H     SI1     61.9  55    337   4.07 4.11 2.53
9     0.22  Fair      E     VS2     65.1  61    337   3.87 3.78 2.49
10    0.23  Very Good H     VS1     59.4  61    338   4.00 4.05 2.39
11    0.30  Good      J     SI1     64.0  55    339   4.25 4.28 2.73
12    0.23  Ideal     J     VS1     62.8  56    340   3.93 3.90 2.46
13    0.22  Premium   F     SI1     60.4  61    342   3.88 3.84 2.33
14    0.31  Ideal     J     SI2     62.2  54    344   4.35 4.37 2.71
15    0.20  Premium   E     SI2     60.2  62    345   3.79 3.75 2.27
16    0.32  Premium   E     I1      60.9  58    345   4.38 4.42 2.68
17    0.30  Ideal     I     SI2     62.0  54    348   4.31 4.34 2.68
18    0.30  Good      J     SI1     63.4  54    351   4.23 4.29 2.70
19    0.30  Good      J     SI1     63.8  56    351   4.23 4.26 2.71
20    0.30  Very Good J     SI1     62.7  59    351   4.21 4.27 2.66
21    0.30  Good      I     SI2     63.3  56    351   4.26 4.30 2.71
22    0.23  Very Good E     VS2     63.8  55    352   3.85 3.92 2.48
23    0.23  Very Good H     VS1     61.0  57    353   3.94 3.96 2.41
24    0.31  Very Good J     SI1     59.4  62    353   4.39 4.43 2.62
25    0.31  Very Good J     SI1     58.1  62    353   4.44 4.47 2.59
26    0.23  Very Good G     VVS2    60.4  58    354   3.97 4.01 2.41
27    0.24  Premium   I     VS1     62.5  57    355   3.97 3.94 2.47
28    0.30  Very Good J     VS2     62.2  57    357   4.28 4.30 2.67
29    0.23  Very Good D     VS2     60.5  61    357   3.96 3.97 2.40
30    0.23  Very Good F     VS1     60.9  57    357   3.96 3.99 2.42
⋮     ⋮     ⋮         ⋮     ⋮       ⋮     ⋮     ⋮     ⋮    ⋮    ⋮   
53911 0.70  Premium   E     SI1     60.5  58    2753  5.74 5.77 3.48
53912 0.57  Premium   E     IF      59.8  60    2753  5.43 5.38 3.23
53913 0.61  Premium   F     VVS1    61.8  59    2753  5.48 5.40 3.36
53914 0.80  Good      G     VS2     64.2  58    2753  5.84 5.81 3.74
53915 0.84  Good      I     VS1     63.7  59    2753  5.94 5.90 3.77
53916 0.77  Ideal     E     SI2     62.1  56    2753  5.84 5.86 3.63
53917 0.74  Good      D     SI1     63.1  59    2753  5.71 5.74 3.61
53918 0.90  Very Good J     SI1     63.2  60    2753  6.12 6.09 3.86
53919 0.76  Premium   I     VS1     59.3  62    2753  5.93 5.85 3.49
53920 0.76  Ideal     I     VVS1    62.2  55    2753  5.89 5.87 3.66
53921 0.70  Very Good E     VS2     62.4  60    2755  5.57 5.61 3.49
53922 0.70  Very Good E     VS2     62.8  60    2755  5.59 5.65 3.53
53923 0.70  Very Good D     VS1     63.1  59    2755  5.67 5.58 3.55
53924 0.73  Ideal     I     VS2     61.3  56    2756  5.80 5.84 3.57
53925 0.73  Ideal     I     VS2     61.6  55    2756  5.82 5.84 3.59
53926 0.79  Ideal     I     SI1     61.6  56    2756  5.95 5.97 3.67
53927 0.71  Ideal     E     SI1     61.9  56    2756  5.71 5.73 3.54
53928 0.79  Good      F     SI1     58.1  59    2756  6.06 6.13 3.54
53929 0.79  Premium   E     SI2     61.4  58    2756  6.03 5.96 3.68
53930 0.71  Ideal     G     VS1     61.4  56    2756  5.76 5.73 3.53
53931 0.71  Premium   E     SI1     60.5  55    2756  5.79 5.74 3.49
53932 0.71  Premium   F     SI1     59.8  62    2756  5.74 5.73 3.43
53933 0.70  Very Good E     VS2     60.5  59    2757  5.71 5.76 3.47
53934 0.70  Very Good E     VS2     61.2  59    2757  5.69 5.72 3.49
53935 0.72  Premium   D     SI1     62.7  59    2757  5.69 5.73 3.58
53936 0.72  Ideal     D     SI1     60.8  57    2757  5.75 5.76 3.50
5393

In [146]:
colorTable <- dbGetQuery(con,"SELECT * FROM DiamondColors",stringsAsFactors=FALSE)

In [147]:
colorTable

Color Description          Details                    
1  D     Absolutely Colorless No color                   
2  E     Colorless            Minute traces of color     
3  F     Colorless            Minute traces of color     
4  G     Near Colorless       Color is dificult to detect
5  H     Near Colorless       Color is dificult to detect
6  I     Near Colorless       Slightly detectable color  
7  J     Near Colorless       Slightly detectable color  
8  K     Faint Color          Noticeable color           
9  L     Faint Color          Noticeable color           
10 M     Faint Color          Noticeable color

In [148]:
longQuery <- "SELECT * FROM diamonds, DiamondColors
WHERE
diamonds.color = DiamondColors.Color"

In [149]:
diamondsJoin <-dbGetQuery(con, longQuery, stringsAsFactors=FALSE)

In [151]:
diamondsJoin

carat cut       color clarity depth table price x    y    z    Color
1     0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43 E    
2     0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31 E    
3     0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31 E    
4     0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63 I    
5     0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75 J    
6     0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48 J    
7     0.24  Very Good I     VVS1    62.3  57    336   3.95 3.98 2.47 I    
8     0.26  Very Good H     SI1     61.9  55    337   4.07 4.11 2.53 H    
9     0.22  Fair      E     VS2     65.1  61    337   3.87 3.78 2.49 E    
10    0.23  Very Good H     VS1     59.4  61    338   4.00 4.05 2.39 H    
11    0.30  Good      J     SI1     64.0  55    339   4.25 4.28 2.73 J    
12    0.23  Ideal     J     VS1     62.8  56    340   3.93 3.90 2.46 J    
13    0.22  Premium   F     SI1     60.4  61    342   3.88 3.84 2.33 F    
14    0.31  Ideal     J     SI2     62.2  54    344   4.35 4.37 2.71 J    
15    0.20  Premium   E     SI2     60.2  62    345   3.79 3.75 2.27 E    
16    0.32  Premium   E     I1      60.9  58    345   4.38 4.42 2.68 E    
17    0.30  Ideal     I     SI2     62.0  54    348   4.31 4.34 2.68 I    
18    0.30  Good      J     SI1     63.4  54    351   4.23 4.29 2.70 J    
19    0.30  Good      J     SI1     63.8  56    351   4.23 4.26 2.71 J    
20    0.30  Very Good J     SI1     62.7  59    351   4.21 4.27 2.66 J    
21    0.30  Good      I     SI2     63.3  56    351   4.26 4.30 2.71 I    
22    0.23  Very Good E     VS2     63.8  55    352   3.85 3.92 2.48 E    
23    0.23  Very Good H     VS1     61.0  57    353   3.94 3.96 2.41 H    
24    0.31  Very Good J     SI1     59.4  62    353   4.39 4.43 2.62 J    
25    0.31  Very Good J     SI1     58.1  62    353   4.44 4.47 2.59 J    
26    0.23  Very Good G     VVS2    60.4  58    354   3.97 4.01 2.41 G    
27    0.24  Premium   I     VS1     62.5  57    355   3.97 3.94 2.47 I    
28    0.30  Very Good J     VS2     62.2  57    357   4.28 4.30 2.67 J    
29    0.23  Very Good D     VS2     60.5  61    357   3.96 3.97 2.40 D    
30    0.23  Very Good F     VS1     60.9  57    357   3.96 3.99 2.42 F    
⋮     ⋮     ⋮         ⋮     ⋮       ⋮     ⋮     ⋮     ⋮    ⋮    ⋮    ⋮    
53911 0.70  Premium   E     SI1     60.5  58    2753  5.74 5.77 3.48 E    
53912 0.57  Premium   E     IF      59.8  60    2753  5.43 5.38 3.23 E    
53913 0.61  Premium   F     VVS1    61.8  59    2753  5.48 5.40 3.36 F    
53914 0.80  Good      G     VS2     64.2  58    2753  5.84 5.81 3.74 G    
53915 0.84  Good      I     VS1     63.7  59    2753  5.94 5.90 3.77 I    
53916 0.77  Ideal     E     SI2     62.1  56    2753  5.84 5.86 3.63 E    
53917 0.74  Good      D     SI1     63.1  59    2753  5.71 5.74 3.61 D    
53918 0.90  Very Good J     SI1     63.2  60    2753  6.12 6.09 3.86 J    
53919 0.76  Premium   I     VS1     59.3  62    2753  5.93 5.85 3.49 I    
53920 0.76  Ideal     I     VVS1    62.2  55    2753  5.89 5.87 3.66 I    
53921 0.70  Very Good E     VS2     62.4  60    2755  5.57 5.61 3.49 E    
53922 0.70  Very Good E     VS2     62.8  60    2755  5.59 5.65 3.53 E    
53923 0.70  Very Good D     VS1     63.1  59    2755  5.67 5.58 3.55 D    
53924 0.73  Ideal     I     VS2     61.3  56    2756  5.80 5.84 3.57 I    
53925 0.73  Ideal     I     VS2     61.6  55    2756  5.82 5.84 3.59 I    
53926 0.79  Ideal     I     SI1     61.6  56    2756  5.95 5.97 3.67 I    
53927 0.71  Ideal     E     SI1     61.9  56    2756  5.71 5.73 3.54 E    
53928 0.79  Good      F     SI1     58.1  59    2756  6.06 6.13 3.54 F    
53929 0.79  Premium   E     SI2     61.4  58    2756  6.03 5.96 3.68 E    
53930 0.71  Ideal     G     VS1     61.4  56    2756  5.76 5.73 3.53 G    
53931 0.71  Premium   E     SI1     60.5  55    2756  5.79 5.74 3.49 E    
53932 0.71  Premium   F     SI1

In [150]:
head(diamondsJoin)

carat cut       color clarity depth table price x    y    z    Color
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43 E    
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31 E    
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31 E    
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63 I    
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75 J    
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48 J    
  Description    Details                  
1 Colorless      Minute traces of color   
2 Colorless      Minute traces of color   
3 Colorless      Minute traces of color   
4 Near Colorless Slightly detectable color
5 Near Colorless Slightly detectable color
6 Near Colorless Slightly detectable color

### 3.4 Data from Other Statistical Tools


In an ideal world another tool besides R would never be needed, but in reality data are sometimes locked
in a proprietary format such as those from SAS, SPSS or Octave. The foreign package provides a number
of functions similar to read.table to read in data from other tools.

### 3.5 R Binary Files PDF --> 0, 1


In [152]:
save(tomato, file="/content/sample_data/tomato.rdata") #save the tomato data.frame to disk 1, 0

In [153]:
rm(tomato) #remove tomato from memory

In [154]:
head(tomato)

ERROR: Error: object 'tomato' not found


In [ ]:
load("/content/sample_data/tomato.rdata")

### 3.6 Data Included with R


R and some packages come with data included, so we can easily have data to use. Accessing this data is
simple as long as we know what to look for. ggplot2, for instance, comes with a dataset about diamonds.
It can be loaded using the data function.

In [155]:
data(diamonds, package='ggplot2')

In [156]:
head(diamonds)

carat cut       color clarity depth table price x    y    z   
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

### 3.7 Extract Data from Web Sites


#### Scraping Web Data

In [157]:
install.packages('rvest')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [158]:
library(rvest)

In [159]:
 ribalta <- read_html('http://www.jaredlander.com/data/ribalta.html')

In [160]:
ribalta

{html_document}
<html xmlns="http://www.w3.org/1999/xhtml">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body>\r\n<ul>\n<li class="address">\r\n    <span class="street">48 E 12t ...

In [161]:
class(ribalta)

[1] "xml_document" "xml_node"

In [162]:
ribalta %>% html_nodes('ul') %>% html_nodes('span')

{xml_nodeset (6)}
[1] <span class="street">48 E 12th St</span>
[2] <span class="city">New York</span>
[3] <span class="zip">10003</span>
[4] <span>\r\n    \t<span id="latitude" value="40.733384"></span>\r\n    \t<s ...
[5] <span id="latitude" value="40.733384"></span>
[6] <span id="longitude" value="-73.9915618"></span>

In [163]:
ribalta %>% html_nodes('.street')

{xml_nodeset (1)}
[1] <span class="street">48 E 12th St</span>

In [164]:
ribalta %>% html_nodes('.street') %>% html_text()

[1] "48 E 12th St"

In [165]:
ribalta %>% html_nodes('#longitude') %>% html_attr('value')

[1] "-73.9915618"

In [166]:
ribalta %>% html_nodes('table.food-items') %>% magrittr::extract2(5) %>% html_table()

X1                     
1 Marinara Pizza Rosse   
2 Doc Pizza Rosse        
3 Vegetariana Pizza Rosse
4 Brigante Pizza Rosse   
5 Calzone Pizza Rosse    
6 Americana Pizza Rosse  
  X2                                                             X3
1 basil, garlic and oregano.                                      9
2 buffalo mozzarella and basil.                                  15
3 mozzarella cheese, basil and baked vegetables.                 15
4 mozzarella cheese, salami and spicy oil.                       15
5 ricotta, mozzarella cheese, prosciutto cotto and black pepper. 16
6 mozzarella cheese, wurstel and fries.                          16

### 3.8 Reading JSON Data


In [167]:
install.packages('jsonlite')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [168]:
library(jsonlite)

In [169]:
pizza <-fromJSON('http://www.jaredlander.com/data/PizzaFavorites.json')

In [170]:
pizza

Name                  
1 Di Fara Pizza         
2 Fiore's Pizza         
3 Juliana's             
4 Keste Pizza & Vino    
5 L & B Spumoni Gardens 
6 New York Pizza Suprema
7 Paulie Gee's          
8 Ribalta               
9 Totonno's             
  Details                                                                   
1 1424 Avenue J, Brooklyn     , NY           , 11230                        
2 165 Bleecker St, New York       , NY             , 10012                  
3 19 Old Fulton St, Brooklyn        , NY              , 11201               
4 271 Bleecker St, New York       , NY             , 10014                  
5 2725 86th St, Brooklyn    , NY          , 11223                           
6 413 8th Ave, New York   , NY         , 10001                              
7 60 Greenpoint Ave, Brooklyn         , NY               , 11222            
8 48 E 12th St, New York    , NY          , 10003                           
9 1524 Neptune Ave, Brooklyn        , NY              , 11224

In [171]:
class(pizza)

[1] "data.frame"

In [172]:
class(pizza$Name)

[1] "character"

In [173]:
class(pizza$Details)

[1] "list"

In [175]:
pizza$Details

[[1]]
        Address     City State   Zip
1 1424 Avenue J Brooklyn    NY 11230

[[2]]
          Address     City State   Zip
1 165 Bleecker St New York    NY 10012

[[3]]
           Address     City State   Zip
1 19 Old Fulton St Brooklyn    NY 11201

[[4]]
          Address     City State   Zip
1 271 Bleecker St New York    NY 10014

[[5]]
       Address     City State   Zip
1 2725 86th St Brooklyn    NY 11223

[[6]]
      Address     City State   Zip
1 413 8th Ave New York    NY 10001

[[7]]
            Address     City State   Zip
1 60 Greenpoint Ave Brooklyn    NY 11222

[[8]]
       Address     City State   Zip
1 48 E 12th St New York    NY 10003

[[9]]
           Address     City State   Zip
1 1524 Neptune Ave Brooklyn    NY 11224

In [176]:
pizza$Details[[1]]

Address       City     State Zip  
1 1424 Avenue J Brooklyn NY    11230

In [174]:
class(pizza$Details[[1]])

[1] "data.frame"